version: 2
updates:
  - package-ecosystem: npm
    directory: '/gatsby-theme-mate'
    schedule:
      interval: weekly
      time: '04:00'
    open-pull-requests-limit: 10
    assignees:
      - EmaSuriano
