version: 2
updates:
  - package-ecosystem: npm
    directory: '/gatsby-theme-mate'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    assignees:
      - EmaSuriano
